services:

  db:
    image: postgres:16
    container_name: securetrack-db
    restart: always

    environment:
      POSTGRES_DB: secure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: securetrack-backend

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env.example

    depends_on:
      - db

  frontend:
    build: ./securetrack-frontend
    container_name: securetrack-frontend

    volumes:
      - ./securetrack-frontend:/app
      - /app/node_modules

    ports:
      - "5173:5173"

    environment:
      - CHOKIDAR_USEPOLLING=true

    depends_on:
      - backend

volumes:
  postgres_data: